# Solver Options
enable_rMIP: false # Enable or disable the relaxed MIP formulation and solving of the model [true/false]
MIP_Gap : 0.0001 # MIP optimality gap for the solver (e.g.: 0.0001 = 0.10%)

# Scenario configuration
case_study: Kanaleneiland # Kanaleneiland, Aradas, Annelinn
LEGO_GPT_path: path to LEGO_GPT.py  # LEGO GPT is not part of the public repository
LEGO_GPT_env_path: path to LEGO_GPT_env (python.exe) # LEGO GPT is not part of the public repository
start_t: 0 # Start time of the scenario
num_t: 48 # Number of time steps in the scenario
year: 2040 # 2035, 2040 or 2050 # For the V2G scenarios only 2040 was considered

# Grid configuration
dc_opf: true # true for DC OPF, false for AC OPF
slack_bus: Node_67 # Sets the slack bus of the network. Node_67 for Kanaleneiland, Node_20 for Aradas, Node_43 for Annelinn
# Voltage soft limits
Enable_Soft_Voltage_Limits: false # Enable or disable soft voltage limits [true/false]
V_soft_limit: 0.05 # Soft voltage limit parameter in p.u. from the hard voltage limits e.g.: Vmax=1.1 p.u.,V_soft_limit=0.05 p.u. then the soft voltage limit is 1.05 p.u.
# Line soft limits
Enable_Soft_Line_Limits: false # Enable or disable soft line limits [true/false]
Line_soft_limit: 0.8  # Soft line limit parameter in percentage from the hard line limits e.g.: Line limit=100 MW, Line_soft_limit=0.8 then the soft line limit is 80 MW.

# Enable or disable generation sources true/false
enable_pv: true # [true/false]
enable_wind: false # [true/false]
enable_hydro: false # [true/false]
pBatt_cap: 8 # Total decentral Storage Capacity for the region in MWh

# Electric Vehicle configuration
pCharge_Invest: 1.3e-3 # Public charger invest per EV in MW

# SOCP relaxation configuration
pQfactor: 0.1 # Power to reactive power demand factor for SOCP relaxation as there are no reactive power demand parameters available
pV_slack: 1 # Voltage at the slack bus in p.u. for SOCP relaxation

# Cost factors
pPenality: 10000 # Penality cost factor for power non served and excess power served in €/MWh applied for node and EV slack variables
pCh_Inf_Cost: 1 # Cost factor for each installed charging infrastructure in €/MW (Set to 1 as we want to insensitive charging infrastructure installation)